services:
  app:
    image: debian:latest
    command:
      - bash
      - -c
      - while true; do echo "$$(date) - $$(cat /run/secrets/my-secret)"; sleep 30; done
    environment:
      - TZ=Asia/Tokyo
    secrets:
      - my-secret
    deploy:
      replicas: 2
      restart_policy:
        delay: 5s

secrets:
  my-secret:
    file: ./my-secret.txt
